apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "api-server"
  namespace: "default"
  labels:
    app: "api-server"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "api-server"
  template:
    metadata:
      labels:
        app: "api-server"
    spec:
      containers:
      - name: "notedly-server-sha256-1"
        image: "mitsukom/notedly-server:latest"
        env:
          - name: GITHUB_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: env
                key: GITHUB_OAUTH_CLIENT_ID
          - name: GITHUB_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: env
                key: GITHUB_OAUTH_CLIENT_SECRET
          - name: GOOGLE_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: env
                key: GOOGLE_OAUTH_CLIENT_ID
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: env
                key: GOOGLE_OAUTH_CLIENT_SECRET
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: env
                key: DATABASE_URL
        ports:
          - containerPort: 80
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api-server-hpa-3r7r"
  namespace: "default"
  labels:
    app: "api-server"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api-server"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "api-request-balancer"
spec:
  selector:
    app: "api-server"
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
