[package]
name = "server"
version = "0.1.0"
authors = ["Dowland Aiello <dowlandaiello@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.6"
reqwest = {version = "0.10.0-alpha.2", features = ["json"]}
snafu = "0.6.0"
sha3 = "0.8.2"
couchbase = "1.0.0-alpha.2"
serde = {version = "1.0.103", features = ["derive"]}
clap = "2.33.0"
