apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helm
  namespace: dev
spec:
  rules:
  - http:
    paths:
    - backend:
        serviceName: notedly
        servicePort: 80
      path: /(.*)
